# Generated by Django 2.2.16 on 2022-03-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20220301_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create',
            new_name='created',
        ),
    ]
