# Generated by Django 2.2.16 on 2022-03-01 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_post_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='follow',
        ),
    ]
